[build]
  command = "astro build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    baseUrl = "https://laec.netlify.app"
    sitemapPath = "/sitemap-index.xml"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"