[build]
  command = "astro build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    baseUrl = "https://shabay.netlify.app"
    sitemapPath = "/sitemap-index.xml"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Scheduled functions for automated notifications
[functions]
  schedule = "*/15 * * * *"  # Run every 15 minutes

# Automated follow-up emails
[[functions]]
  path = "automated-followups"
  schedule = "*/30 * * * *"  # Every 30 minutes

# Appointment reminders
[[functions]]
  path = "send-appointment-reminders"
  schedule = "0 8,12,16 * * *"  # 8am, 12pm, 4pm daily

# Scheduled reminders
[[functions]]
  path = "scheduled-reminders"
  schedule = "0 9 * * *"  # 9am daily