# Shallow Bay Advisors CMS Configuration
backend:
  name: git-gateway
  branch: main

# Site configuration
site_url: https://shabay.netlify.app
display_url: https://shabay.netlify.app
logo_url: https://shabay.netlify.app/images/uploads/sbalogo.png

# Media and public folders
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Publishing workflow
publish_mode: editorial_workflow

# Collections
collections:
  # Properties Collection
  - name: "properties"
    label: "Properties"
    folder: "src/content/properties"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Property Type", name: "type", widget: "select", options: ["warehouse", "office", "industrial", "flex-space", "distribution"] }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "County", name: "county", widget: "select", options: ["Miami-Dade", "Broward", "Palm Beach"] }
      - { label: "Price per sqft", name: "price", widget: "string", hint: "e.g., $8.50" }
      - { label: "Square Footage", name: "size", widget: "string", hint: "e.g., 25,000" }
      - { label: "Available", name: "available", widget: "boolean", default: true }
      - { label: "Featured Property", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Property Image", name: "image", widget: "image", required: false }
      - label: "Features"
        name: "features"
        widget: "list"
        field: { label: "Feature", name: "feature", widget: "string" }
        default: ["Dock High", "Highway Access"]
      - label: "Additional Images"
        name: "gallery"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
        required: false
      - { label: "Contact Name", name: "contact_name", widget: "string", required: false }
      - { label: "Contact Email", name: "contact_email", widget: "string", required: false }
      - { label: "Contact Phone", name: "contact_phone", widget: "string", required: false }
      - { label: "Address", name: "address", widget: "string", required: false }
      - { label: "Lease Term", name: "lease_term", widget: "string", required: false, hint: "e.g., 5 years" }
      - { label: "Clear Height", name: "clear_height", widget: "string", required: false, hint: "e.g., 32 feet" }
      - { label: "Loading Docks", name: "loading_docks", widget: "number", required: false }
      - { label: "Parking Spaces", name: "parking", widget: "number", required: false }
      - { label: "Year Built", name: "year_built", widget: "number", required: false }
      - { label: "Listing Date", name: "date", widget: "datetime", default: "{{now}}" }

  # Leads Collection
  - name: "leads"
    label: "Leads & Inquiries"
    folder: "src/content/leads"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    editor:
      preview: false
    fields:
      - { label: "Lead ID", name: "title", widget: "string", default: "Lead {{now}}" }
      - { label: "Lead Type", name: "type", widget: "select", options: ["consultation", "property-inquiry", "general-inquiry", "contact-form"] }
      - { label: "Status", name: "status", widget: "select", options: ["new", "contacted", "qualified", "proposal-sent", "closed-won", "closed-lost"], default: "new" }
      - { label: "Priority", name: "priority", widget: "select", options: ["low", "medium", "high", "urgent"], default: "medium" }
      - { label: "Full Name", name: "name", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string", required: false }
      - { label: "Company", name: "company", widget: "string", required: false }
      - { label: "Property Interest", name: "property_interest", widget: "string", required: false }
      - { label: "Space Requirements", name: "space_requirements", widget: "text", required: false }
      - { label: "Budget Range", name: "budget", widget: "string", required: false }
      - { label: "Timeline", name: "timeline", widget: "string", required: false }
      - { label: "Message/Notes", name: "message", widget: "text", required: false }
      - { label: "Source", name: "source", widget: "select", options: ["website", "referral", "cold-call", "email-campaign", "social-media", "trade-show", "other"], default: "website" }
      - { label: "Consultation Date", name: "consultation_date", widget: "datetime", required: false }
      - { label: "Consultation Time", name: "consultation_time", widget: "string", required: false }
      - { label: "Follow-up Date", name: "follow_up_date", widget: "datetime", required: false }
      - { label: "Internal Notes", name: "internal_notes", widget: "text", required: false }
      - { label: "Date Created", name: "date", widget: "datetime", default: "{{now}}" }

  # Blog Posts (Optional)
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Shallow Bay Advisors" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" }, required: false }
      - { label: "Category", name: "category", widget: "select", options: ["commercial-real-estate", "warehouse", "industrial", "market-insights", "tips", "news"], default: "commercial-real-estate" }
      - { label: "Featured Post", name: "featured", widget: "boolean", default: false }
      - { label: "Publish Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Body", name: "body", widget: "markdown" }

  # Site Settings
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "src/content/settings/general.yml"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string", default: "Shallow Bay Advisors" }
          - { label: "Site Description", name: "site_description", widget: "text", default: "South Florida's premier commercial real estate advisors" }
          - { label: "Contact Email", name: "contact_email", widget: "string" }
          - { label: "Contact Phone", name: "contact_phone", widget: "string" }
          - { label: "Office Address", name: "office_address", widget: "text" }
          - { label: "Business Hours", name: "business_hours", widget: "text", default: "Monday - Friday: 9AM - 6PM" }
          - { label: "Social Media Links", name: "social_links", widget: "object", fields: [
              { label: "LinkedIn", name: "linkedin", widget: "string", required: false },
              { label: "Twitter", name: "twitter", widget: "string", required: false },
              { label: "Facebook", name: "facebook", widget: "string", required: false },
              { label: "Instagram", name: "instagram", widget: "string", required: false }
            ]}
          - { label: "Google Analytics ID", name: "google_analytics", widget: "string", required: false }
          - { label: "Site Logo", name: "logo", widget: "image", required: false }