# Shallow Bay Advisors CMS Configuration
backend:
  name: git-gateway
  branch: main

# Site configuration
site_url: https://shabay.netlify.app
display_url: https://shabay.netlify.app
logo_url: https://shabay.netlify.app/images/uploads/sbalogo.png

# Media and public folders
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Publishing workflow
publish_mode: editorial_workflow

# Professional UI styling
editor:
  preview: false
  frame: true

# Collections
collections:
  # Properties Collection
  - name: "properties"
    label: "Properties"
    folder: "src/content/properties"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      # Basic Information
      - { label: "Property Title", name: "title", widget: "string", hint: "Enter the property name or description" }
      - { label: "Location", name: "location", widget: "string", hint: "City or area (e.g., Doral, Miami)" }
      - { label: "County", name: "county", widget: "select", options: ["Miami-Dade", "Broward", "Palm Beach"] }

      # Property Details
      - { label: "Price per Square Foot", name: "price", widget: "string", hint: "Include $ symbol (e.g., $8.50)" }
      - { label: "Square Footage", name: "size", widget: "string", hint: "Total square feet (e.g., 25,000)" }
      - { label: "Available for Lease", name: "available", widget: "boolean", default: true }
      - { label: "Featured Property", name: "featured", widget: "boolean", default: false, required: false, hint: "Display prominently on homepage" }

      # Media
      - { label: "Main Property Image", name: "image", widget: "image", hint: "Primary photo for property listing" }
      - label: "Additional Images"
        name: "gallery"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
        required: false
        hint: "Upload multiple photos (unlimited)"

      # Location Details
      - { label: "Street Address", name: "street_address", widget: "string", hint: "Street number and name (e.g., 123 Main Street)", required: false }
      - { label: "City", name: "city", widget: "string", hint: "City name (e.g., Miami, Doral)", required: false }
      - { label: "State", name: "state", widget: "string", default: "FL", hint: "State abbreviation", required: false }
      - { label: "ZIP Code", name: "zip_code", widget: "string", hint: "5-digit ZIP code", required: false }

      # Property Features
      - label: "Property Features"
        name: "features"
        widget: "list"
        field: { label: "Feature", name: "feature", widget: "string" }
        default: ["Dock High", "Highway Access"]
        hint: "List key property amenities and features"

      # Advanced Details (Optional)
      - { label: "Clear Height", name: "clear_height", widget: "string", required: false, hint: "Ceiling height (e.g., 32 feet)" }
      - { label: "Loading Docks", name: "loading_docks", widget: "number", required: false, hint: "Number of dock doors" }
      - { label: "Year Built", name: "year_built", widget: "number", required: false, hint: "Construction year" }
      - { label: "Lease Term", name: "lease_term", widget: "string", required: false, hint: "Available lease duration (e.g., 5 years)" }

      # System Fields
      - { label: "Listing Date", name: "date", widget: "datetime" }

  # Leads Collection
  - name: "leads"
    label: "Leads & Inquiries"
    folder: "src/content/leads"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    editor:
      preview: false
    fields:
      - { label: "Lead ID", name: "title", widget: "string", default: "Lead {{now}}" }
      - { label: "Lead Type", name: "type", widget: "select", options: ["consultation", "property-inquiry", "general-inquiry", "contact-form"] }
      - { label: "Status", name: "status", widget: "select", options: ["new", "contacted", "qualified", "proposal-sent", "closed-won", "closed-lost"], default: "new" }
      - { label: "Priority", name: "priority", widget: "select", options: ["low", "medium", "high", "urgent"], default: "medium" }
      - { label: "Full Name", name: "name", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string", required: false }
      - { label: "Company", name: "company", widget: "string", required: false }
      - { label: "Property Interest", name: "property_interest", widget: "string", required: false }
      - { label: "Space Requirements", name: "space_requirements", widget: "text", required: false }
      - { label: "Budget Range", name: "budget", widget: "string", required: false }
      - { label: "Timeline", name: "timeline", widget: "string", required: false }
      - { label: "Message/Notes", name: "message", widget: "text", required: false }
      - { label: "Source", name: "source", widget: "select", options: ["website", "referral", "cold-call", "email-campaign", "social-media", "trade-show", "other"], default: "website" }
      - { label: "Consultation Date", name: "consultation_date", widget: "datetime", required: false }
      - { label: "Consultation Time", name: "consultation_time", widget: "string", required: false }
      - { label: "Follow-up Date", name: "follow_up_date", widget: "datetime", required: false }
      - { label: "Internal Notes", name: "internal_notes", widget: "text", required: false }
      - { label: "Date Created", name: "date", widget: "datetime" }


  # Site Settings
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "src/content/settings/general.yml"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string", default: "Shallow Bay Advisors" }
          - { label: "Site Description", name: "site_description", widget: "text", default: "South Florida's premier commercial real estate advisors" }
          - { label: "Contact Email", name: "contact_email", widget: "string" }
          - { label: "Contact Phone", name: "contact_phone", widget: "string" }
          - { label: "Office Address", name: "office_address", widget: "text" }
          - { label: "Business Hours", name: "business_hours", widget: "text", default: "Monday - Friday: 9AM - 6PM" }
          - { label: "Social Media Links", name: "social_links", widget: "object", fields: [
              { label: "LinkedIn", name: "linkedin", widget: "string", required: false },
              { label: "Twitter", name: "twitter", widget: "string", required: false },
              { label: "Facebook", name: "facebook", widget: "string", required: false },
              { label: "Instagram", name: "instagram", widget: "string", required: false }
            ]}
          - { label: "Google Analytics ID", name: "google_analytics", widget: "string", required: false }
          - { label: "Site Logo", name: "logo", widget: "image", required: false }

      - name: "locations"
        label: "Service Areas & Markets"
        file: "src/content/settings/locations.yml"
        fields:
          - label: "Active Markets"
            name: "markets"
            widget: "list"
            fields:
              - { label: "State", name: "state", widget: "string", hint: "e.g., Florida" }
              - { label: "State Code", name: "state_code", widget: "string", hint: "e.g., FL" }
              - label: "Counties"
                name: "counties"
                widget: "list"
                fields:
                  - { label: "County Name", name: "name", widget: "string", hint: "e.g., Miami-Dade" }
                  - { label: "Active", name: "active", widget: "boolean", default: true }
                  - { label: "Primary Market", name: "primary", widget: "boolean", default: false, hint: "Mark as main market area" }